name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.0
author: InspireUI
homepage: https://inspireui.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: 1.0.0
  sensors: 2.0.3
  google_fonts: 2.0.0
  event_bus: 2.0.0
